import { Router } from "express";
import { middleware_existCart } from "../middlewares/existeCart.middleware.js";
import { middleware_existProd } from "../middlewares/existProd.middleware.js";
import { middleware_existProdInCart } from "../middlewares/existProdInCart.middleware.js";
import { middleware_existProdArray } from "../middlewares/existProdArray.middleware.js"

import * as controller from "../controllers/cart.controller.js";

const router = Router();

router.post('/', controller.createCart)                  //Create Cart. Data on body. Id Autogenerated.

router.get('/:cid', middleware_existCart, controller.getCartById)                //Get Products on cart CId.

router.post('/:cid/products/:pid', middleware_existProd, middleware_existCart, controller.addProductToCart)  //Add Product PId to cart CId. 

router.delete('/:cid/products/:pid', middleware_existCart, middleware_existProd, middleware_existProdInCart, controller.deleteProductFromCart) //Delete Product

router.put('/:cid', middleware_existProdArray, controller.updateCart)    // actualizar el carrito con un arreglo de productos con el formato especificado arriba.

router.put('/:cid/products/:pid', middleware_existProd, middleware_existCart, middleware_existProdInCart, controller.updateQuantity) //update quantity from body

router.delete('/:cid', middleware_existCart, controller.deleteCart)

export default router;


    /*Cart data:
        {
            id:
            products: Array de Products
        }
    */
    /*Product in cart format:
        {
            product: productId
            quantity: (add 1 every time method is called)
        }
    */