import { Router } from "express";
import { ProductManager } from "../daos/filesystem/product.dao.js"
import {__dirname} from "../utils.js"
import { middleware_createProd } from "../middlewares/createProduct.midleware.js";
import { middleware_updProd } from "../middlewares/updateProd.midleware.js";
import { socketServer } from "../server.js";
import * as controller from "../controllers/product.controller.js";

const productManager = new ProductManager(`${__dirname}/daos/filesystem/products.json`);
const router = Router();

router.get('/', controller.getProducts)               //Get ALL products

router.get('/:pid', controller.getProductById)           //Get PId Product

router.post('/', middleware_createProd, controller.createProduct)               //Create Product. Data on body. Id Autogenerated

router.put('/:pid', middleware_updProd, controller.updateProduct)            //Update Product. Data on body. Id unchanged.

router.delete('/:pid', controller.deleteProduct)          //Delete Product. 

export default router;


        /*Product data:
            {   
                id:
                title: 
                description:
                code: 
                price:
                status: 
                stock:
                category:
                thumbnail: []   //Array of thumbnail paths
            }    
        */