import { Router } from "express"
import {__dirname} from "../utils.js"
import { middleware_createProd } from "../middlewares/createProduct.midleware.js";
import { middleware_updProd } from "../middlewares/updateProd.midleware.js";
import { middleware_existProd } from "../middlewares/existProd.middleware.js";
import * as controller from "../controllers/product.controller.js";

const router = Router();

router.get('/', controller.getProducts)               //Get ALL products

router.get('/:pid', middleware_existProd, controller.getProductById)           //Get PId Product

router.post('/', middleware_createProd, controller.createProduct)               //Create Product. Data on body. Id Autogenerated

router.put('/:pid', middleware_updProd, controller.updateProduct)            //Update Product. Data on body. Id unchanged.

router.delete('/:pid', middleware_existProd, controller.deleteProduct)          //Delete Product. 

export default router;