import { Router } from "express";
import { __dirname } from "../utils/__dirname.js";
import { middleware_updProd } from "../middlewares/updateProd.midleware.js";
import { middleware_existProd } from "../middlewares/existProd.middleware.js";
import { productController } from "../controllers/product.controller.js";
import { authorizations } from "../middlewares/authorization.middleware.js";
import { productDto } from "../dtos/product.dto.js";
import { validate } from "../middlewares/validation.middleware.js";
import passport from "passport";

const router = Router();

router.get("/", productController.getProducts); //Get ALL products

router.get("/:pid", middleware_existProd, productController.getProductById); //Get PId Product

router.post(
	"/",
	passport.authenticate("current", { session: false }),
	validate(productDto),
	authorizations(["admin"]),
	productController.createProduct
); //Create Product. Data on body. Id Autogenerated

router.put(
	"/:pid",
	middleware_existProd,
	middleware_updProd,
	authorizations(["admin"]),
	productController.updateProduct
); //Update Product. Data on body. Id unchanged.

router.delete(
	"/:pid",
	middleware_existProd,
	authorizations(["admin"]),
	productController.deleteProduct
); //Delete Product.

export default router;
